impl cypher in k8s
Committed-by: Diwen Zhu from Dev container

Committed-by: Diwen Zhu from Dev container

diff --git a/interactive_engine/assembly/src/bin/graphscope/giectl b/interactive_engine/assembly/src/bin/graphscope/giectl
--- a/interactive_engine/assembly/src/bin/graphscope/giectl
+++ b/interactive_engine/assembly/src/bin/graphscope/giectl
@@ -338,22 +338,42 @@ create_gremlin_instance_on_k8s() {
   log "Expose gremlin server."
   timeout_seconds=60
   # random from range [50001, 51000) for interactive engine
-  frontend_external_port=$(( ((RANDOM<<15)|RANDOM) % 1000 + 50000 ))
+  frontend_external_gremlin_port=$(( ((RANDOM<<15)|RANDOM) % 1000 + 50000 ))
+  frontend_external_cypher_port=$(( ((RANDOM<<15)|RANDOM) % 1000 + 50000 ))
   frontend_deployment_name=$(kubectl get deployment -lapp.kubernetes.io/component=frontend,app.kubernetes.io/instance=${instance_id},app.kubernetes.io/engine_selector=${engine_selector} -o jsonpath='{.items[*].metadata.name}')
   if [ "${GREMLIN_EXPOSE}" = "LoadBalancer" ]; then
-    kubectl expose deployment ${frontend_deployment_name} --name=gremlin-${object_id} --port=${frontend_external_port} \
+    # gremlin
+    kubectl expose deployment ${frontend_deployment_name} --name=gremlin-${object_id} --port=${frontend_external_gremlin_port} \
       --target-port=${frontend_gremlin_port} --type=LoadBalancer 1>/dev/null 2>&1
     [ $? -eq 0 ] || exit 1
     wait_period_seconds=0
     while true
     do
-      external_ip=$(kubectl get service gremlin-${object_id} -ojsonpath='{.status.loadBalancer.ingress[0].ip}') || true
-      if [ -n "${external_ip}" ]; then
+      external_gremlin_ip=$(kubectl get service gremlin-${object_id} -ojsonpath='{.status.loadBalancer.ingress[0].ip}') || true
+      if [ -n "${external_gremlin_ip}" ]; then
         break
       fi
       wait_period_seconds=$(($wait_period_seconds+5))
       if [ ${wait_period_seconds} -gt ${timeout_seconds} ];then
-        echo "Get external ip of ${GREMLIN_EXPOSE} failed."
+        echo "Get gremlin external ip of ${GREMLIN_EXPOSE} failed."
+        break
+      fi
+      sleep 5
+    done
+    # cypher
+    kubectl expose deployment ${frontend_deployment_name} --name=cypher-${object_id} --port=${frontend_external_cypher_port} \
+      --target-port=${frontend_cypher_port} --type=LoadBalancer 1>/dev/null 2>&1
+    [ $? -eq 0 ] || exit 1
+    wait_period_seconds=0
+    while true
+    do
+      external_cypher_ip=$(kubectl get service cypher-${object_id} -ojsonpath='{.status.loadBalancer.ingress[0].ip}') || true
+      if [ -n "${external_cypher_ip}" ]; then
+        break
+      fi
+      wait_period_seconds=$(($wait_period_seconds+5))
+      if [ ${wait_period_seconds} -gt ${timeout_seconds} ];then
+        echo "Get cypher external ip of ${GREMLIN_EXPOSE} failed."
         break
       fi
       sleep 5
@@ -361,14 +381,14 @@ create_gremlin_instance_on_k8s() {
   else
     # NodePort service type
     # expose gremlin service
-    kubectl expose deployment ${frontend_deployment_name} --name=gremlin-${object_id} --port=${frontend_external_port} \
+    kubectl expose deployment ${frontend_deployment_name} --name=gremlin-${object_id} --port=${frontend_external_gremlin_port} \
       --target-port=${frontend_gremlin_port} --type=NodePort 1>/dev/null 2>&1
     [ $? -eq 0 ] || exit 1
     wait_period_seconds=0
     while true
     do
-      frontend_external_port=$(kubectl describe services gremlin-${object_id} | grep "NodePort" | grep "TCP" | tr -cd "0-9")
-      if [ -n "${frontend_external_port}" ]; then
+      frontend_external_gremlin_port=$(kubectl describe services gremlin-${object_id} | grep "NodePort" | grep "TCP" | tr -cd "0-9")
+      if [ -n "${frontend_external_gremlin_port}" ]; then
         break
       fi
       wait_period_seconds=$(($wait_period_seconds+5))
@@ -381,13 +401,45 @@ create_gremlin_instance_on_k8s() {
     wait_period_seconds=0
     while true
     do
-      external_ip=$(kubectl describe pods ${frontend_deployment_name} | grep "Node:" | head -1 | awk -F '[ /]+' '{print $3}')
-      if [ -n "${external_ip}" ]; then
+      external_gremlin_ip=$(kubectl describe pods ${frontend_deployment_name} | grep "Node:" | head -1 | awk -F '[ /]+' '{print $3}')
+      if [ -n "${external_gremlin_ip}" ]; then
         break
       fi
       wait_period_seconds=$(($wait_period_seconds+5))
       if [ ${wait_period_seconds} -gt ${timeout_seconds} ];then
-        log "Get interactive engine frontend host ip of ${GREMLIN_EXPOSE} failed."
+        log "Get interactive engine frontend gremlin host ip of ${GREMLIN_EXPOSE} failed."
+        break
+      fi
+      sleep 5
+    done
+    # expose cypher service
+    kubectl expose deployment ${frontend_deployment_name} --name=cypher-${object_id} --port=${frontend_external_cypher_port} \
+      --target-port=${frontend_cypher_port} --type=NodePort 1>/dev/null 2>&1
+    [ $? -eq 0 ] || exit 1
+    wait_period_seconds=0
+    while true
+    do
+      frontend_external_cypher_port=$(kubectl describe services cypher-${object_id} | grep "NodePort" | grep "TCP" | tr -cd "0-9")
+      if [ -n "${frontend_external_cypher_port}" ]; then
+        break
+      fi
+      wait_period_seconds=$(($wait_period_seconds+5))
+      if [ ${wait_period_seconds} -gt ${timeout_seconds} ];then
+        log "Get interactive engine frontend node port failed."
+        break
+      fi
+      sleep 5
+    done
+    wait_period_seconds=0
+    while true
+    do
+      external_cypher_ip=$(kubectl describe pods ${frontend_deployment_name} | grep "Node:" | head -1 | awk -F '[ /]+' '{print $3}')
+      if [ -n "${external_cypher_ip}" ]; then
+        break
+      fi
+      wait_period_seconds=$(($wait_period_seconds+5))
+      if [ ${wait_period_seconds} -gt ${timeout_seconds} ];then
+        log "Get interactive engine frontend cypher host ip of ${GREMLIN_EXPOSE} failed."
         break
       fi
       sleep 5
@@ -396,7 +448,9 @@ create_gremlin_instance_on_k8s() {
   # currently support only 1 pod.
   frontend_ip=$(kubectl get pod -lapp.kubernetes.io/component=frontend,app.kubernetes.io/instance=${instance_id} -o jsonpath='{.items[*].status.podIP}')
   log "FRONTEND_GREMLIN_ENDPOINT:${frontend_ip}:${frontend_gremlin_port}"
-  log "FRONTEND_EXTERNAL_GREMLIN_ENDPOINT:${external_ip}:${frontend_external_port}"
+  log "FRONTEND_EXTERNAL_GREMLIN_ENDPOINT:${external_gremlin_ip}:${frontend_external_gremlin_port}"
+  log "FRONTEND_CYPHER_ENDPOINT:${frontend_ip}:${frontend_cypher_port}"
+  log "FRONTEND_EXTERNAL_CYPHER_ENDPOINT:${external_cypher_ip}:${frontend_external_cypher_port}"
   exit 0
 }
 
@@ -449,6 +503,8 @@ close_gremlin_instance_on_k8s() {
   # delete service
   log "delete gremlin service"
   kubectl delete service gremlin-${object_id} || true
+  log "delete cypher service"
+  kubectl delete service cypher-${object_id} || true
 
   # kill frontend and coordinator process
   log "Close frontend process."
