minor update.

diff --git a/flex/flexbuild b/flex/flexbuild
--- a/flex/flexbuild
+++ b/flex/flexbuild
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 0.8.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -68,6 +68,8 @@ root_command() {
 
   SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
+  ars=()
+
   output_dir=`realpath ${args[--output_dir]}`
   mkdir -p ${output_dir}
 
@@ -83,6 +85,7 @@ root_command() {
     cmd="cmake -DCPACK_PACKAGE_NAME=${package_name} ${SCRIPT_DIR} && make -j && make package && mv ${package_name}*.deb ${output_dir}/"
     echo $cmd
     eval $cmd
+    ars+=("${output_dir}/${package_name}*.deb")
     popd > /dev/null
   elif [ ${args[--app]} == "olap" ]; then
     target_name="graphscope_flex_${args[--app]}"
@@ -96,6 +99,7 @@ root_command() {
     elif [[ " ${comps[*]} " =~ " grape-gpu " ]]; then
       build_grape_gpu ${output_dir}/${target_name}
     fi
+    ars+=("${output_dir}/${target_name}")
   elif [ ${args[--app]} == "ldbcdriver" ]; then
     target_name="graphscope_flex_olap"
     comps=""
@@ -116,10 +120,29 @@ root_command() {
     package_name="${package_name}-SNAPSHOT-bin.tar.gz"
 
     build_grape_ldbc_driver ${output_dir}/${package_name}
+    ars+=("${output_dir}/${package_name}")
+
+  elif [ ${args[--app]} == "gnn" ]; then
+    target_name="graphscope_flex_gnn_gnnmodels_graphlearn_tensorflow_vineyard"
+    pushd ${SCRIPT_DIR}/../ > /dev/null
+    make learning
+    mv learning_engine/graph-learn/graphlearn/built/lib/libgraphlearn_shared* ${output_dir}/
+    fname=`ls ${output_dir}/libgraphlearn_shared*`
+    ext="${fname##*.}"
+    mv ${output_dir}/${fname} ${output_dir}/${target_name}.${ext}
+    ars+=("${output_dir}/${target_name}.${ext}")
+    popd > /dev/null
+  else
+    echo "$(red Unsupported composition: ${args[--app]} and ${args[components]})"
   fi
 
-  # TODO: parse args and make.
-  # echo "artifact: graphscope_flex_${args[--app]}_"+${$comps// /_}+".deb is built."
+  echo "$(green_bold GraphScope Flex artifacts for customized deployment are built.)"
+  echo
+
+  echo "artifacts: "
+  for x in "${ars[@]}"; do
+    echo "$(green x) )"
+  done
 
 }
 
@@ -140,7 +163,7 @@ flexbuild_usage() {
 
   fi
 
-  printf "%s\n" "Usage:"
+  printf "Usage:\n"
   printf "  flexbuild COMPONENTS... [OPTIONS]\n"
   printf "  flexbuild --help | -h\n"
   printf "  flexbuild --version | -v\n"
@@ -148,40 +171,41 @@ flexbuild_usage() {
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "%s\n" "Options:"
-
-    # :command.usage_flags
-    # :flag.usage
-    printf "  %s\n" "--app, -a ATYPE (required)"
-    printf "    Application type.\n"
-    printf "    Allowed: db, olap, ldbcdriver\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "--output_dir, -o NAME"
-    printf "\n"
-    printf "    Default: .\n"
-    echo
+    printf "Options:\n"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    echo "  --help, -h"
     printf "    Show this help\n"
     echo
-    printf "  %s\n" "--version, -v"
+    echo "  --version, -v"
     printf "    Show version number\n"
     echo
 
+    # :command.usage_flags
+    # :flag.usage
+    echo "  --app, -a ATYPE (required)"
+    printf "    Application type\n"
+    printf "    Allowed: db, olap, ldbcdriver, gnn\n"
+    echo
+
+    # :flag.usage
+    echo "  --output_dir, -o NAME"
+    printf "    Output prefix\n"
+    printf "    Default: .\n"
+    echo
+
     # :command.usage_args
-    printf "%s\n" "Arguments:"
+    printf "Arguments:\n"
 
     # :argument.usage
-    printf "  %s\n" "COMPONENTS..."
-    printf "    components to include and link\n"
+    echo "  COMPONENTS..."
+    printf "    Components (LEGO bricks) to include and link\n"
+    printf "    Allowed: cppsp, builtin, hiactor, gaia, grape-cpu, grape-gpu, vineyard, mcsr\n"
     echo
 
     # :command.usage_examples
-    printf "%s\n" "Examples:"
-    printf "  ./flexbuild cppsp hiactor --app db --output_dir ./output\n"
+    printf "Examples:\n"
+    printf "  ./flexbuild cppsp hiactor mcsr --app db --output_dir ./output\n"
     printf "  ./flexbuild builtin grape-cpu --app olap\n"
     printf "  ./flexbuild builtin grape-gpu --app ldbcdriver\n"
     echo
@@ -203,7 +227,7 @@ normalize_input() {
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
       flags="${BASH_REMATCH[1]}"
-      for ((i = 0; i < ${#flags}; i++)); do
+      for (( i=0 ; i < ${#flags} ; i++ )); do
         input+=("-${flags:i:1}")
       done
     else
@@ -215,15 +239,15 @@ normalize_input() {
 }
 # :command.inspect_args
 inspect_args() {
-  if ((${#args[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
+  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
+  if (( ${#args[@]} )); then
     echo args:
     for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
     echo args: none
   fi
 
-  if ((${#other_args[@]})); then
+  if (( ${#other_args[@]} )); then
     echo
     echo other_args:
     echo "- \${other_args[*]} = ${other_args[*]}"
@@ -231,40 +255,59 @@ inspect_args() {
       echo "- \${other_args[$i]} = ${other_args[$i]}"
     done
   fi
-
-  if ((${#deps[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
-    echo
-    echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
-  fi
-
 }
+
+# :command.user_lib
+# src/lib/colors.sh
+print_in_color() {
+  local color="$1"
+  shift
+  if [[ -z ${NO_COLOR+x} ]]; then
+    printf "$color%b\e[0m\n" "$*";
+  else
+    printf "%b\n" "$*";
+  fi
+}
+
+red() { print_in_color "\e[31m" "$*"; }
+green() { print_in_color "\e[32m" "$*"; }
+yellow() { print_in_color "\e[33m" "$*"; }
+blue() { print_in_color "\e[34m" "$*"; }
+magenta() { print_in_color "\e[35m" "$*"; }
+cyan() { print_in_color "\e[36m" "$*"; }
+bold() { print_in_color "\e[1m" "$*"; }
+underlined() { print_in_color "\e[4m" "$*"; }
+red_bold() { print_in_color "\e[1;31m" "$*"; }
+green_bold() { print_in_color "\e[1;32m" "$*"; }
+yellow_bold() { print_in_color "\e[1;33m" "$*"; }
+blue_bold() { print_in_color "\e[1;34m" "$*"; }
+magenta_bold() { print_in_color "\e[1;35m" "$*"; }
+cyan_bold() { print_in_color "\e[1;36m" "$*"; }
+red_underlined() { print_in_color "\e[4;31m" "$*"; }
+green_underlined() { print_in_color "\e[4;32m" "$*"; }
+yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
+blue_underlined() { print_in_color "\e[4;34m" "$*"; }
+magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
+cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
 # :command.command_functions
 
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
-      --version | -v)
-        version_command
-        exit
-        ;;
+  case "${1:-}" in
+  --version | -v )
+    version_command
+    exit
+    ;;
 
-      --help | -h)
-        long_usage=yes
-        flexbuild_usage
-        exit
-        ;;
+  --help | -h )
+    long_usage=yes
+    flexbuild_usage
+    exit
+    ;;
 
-      *)
-        break
-        ;;
-
-    esac
-  done
+  esac
 
   # :command.command_filter
   action="root"
@@ -273,76 +316,83 @@ parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
-      --app | -a)
+    # :flag.case
+    --app | -a )
 
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
+      # :flag.case_arg
+      if [[ -n ${2+x} ]]; then
 
-          args['--app']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--app requires an argument: --app, -a ATYPE" >&2
-          exit 1
-        fi
-        ;;
-
-      # :flag.case
-      --output_dir | -o)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-
-          args['--output_dir']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--output_dir requires an argument: --output_dir, -o NAME" >&2
-          exit 1
-        fi
-        ;;
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        args[--app]="$2"
+        shift
+        shift
+      else
+        printf "%s\n" "--app requires an argument: --app, -a ATYPE" >&2
         exit 1
-        ;;
+      fi
+      ;;
 
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_repeatable
+    # :flag.case
+    --output_dir | -o )
 
-        if [[ -z ${args['components']+x} ]]; then
-          args['components']="\"$1\""
-          shift
-        else
-          args['components']="${args[components]} \"$1\""
-          shift
-        fi
+      # :flag.case_arg
+      if [[ -n ${2+x} ]]; then
 
-        ;;
+        args[--output_dir]="$2"
+        shift
+        shift
+      else
+        printf "%s\n" "--output_dir requires an argument: --output_dir, -o NAME" >&2
+        exit 1
+      fi
+      ;;
+
+    -?* )
+      printf "invalid option: %s\n" "$key" >&2
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_repeatable
+      if [[ -z ${args[components]+x} ]]; then
+
+        args[components]="\"$1\""
+        shift
+      else
+        args[components]="${args[components]} \"$1\""
+        shift
+      fi
+
+      ;;
 
     esac
   done
 
   # :command.required_args_filter
-  if [[ -z ${args['components']+x} ]]; then
+  if [[ -z ${args[components]+x} ]]; then
     printf "missing required argument: COMPONENTS\nusage: flexbuild COMPONENTS... [OPTIONS]\n" >&2
     exit 1
   fi
 
   # :command.required_flags_filter
-  if [[ -z ${args['--app']+x} ]]; then
+  if [[ -z ${args[--app]+x} ]]; then
     printf "missing required flag: --app, -a ATYPE\n" >&2
     exit 1
   fi
 
   # :command.default_assignments
-  [[ -n ${args['--output_dir']:-} ]] || args['--output_dir']="."
+  [[ -n ${args[--output_dir]:-} ]] || args[--output_dir]="."
 
   # :command.whitelist_filter
-  if [[ ${args['--app']} ]] && [[ ! ${args['--app']} =~ ^(db|olap|ldbcdriver)$ ]]; then
-    printf "%s\n" "--app must be one of: db, olap, ldbcdriver" >&2
+  eval "input_array=(${args[components]})"
+  for i in "${input_array[@]}"; do
+    if [[ ! $i =~ ^(cppsp|builtin|hiactor|gaia|grape-cpu|grape-gpu|vineyard|mcsr)$ ]]; then
+      printf "%s\n" "components must be one of: cppsp, builtin, hiactor, gaia, grape-cpu, grape-gpu, vineyard, mcsr" >&2
+      exit 1
+    fi
+  done
+  if [[ ! ${args[--app]} =~ ^(db|olap|ldbcdriver|gnn)$ ]]; then
+    printf "%s\n" "--app must be one of: db, olap, ldbcdriver, gnn" >&2
     exit 1
   fi
 
@@ -361,15 +411,14 @@ initialize() {
 # :command.run
 run() {
   declare -A args=()
-  declare -A deps=()
   declare -a other_args=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
-  case "$action" in
-    "root") root_command ;;
-  esac
+  if [[ $action == "root" ]]; then
+    root_command
+  fi
 }
 
 initialize
