update bashly

diff --git a/flex/flexbuild b/flex/flexbuild
--- a/flex/flexbuild
+++ b/flex/flexbuild
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 0.9.3 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.6 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -16,8 +16,29 @@ root_command() {
   echo "# you can edit it freely and regenerate (it will not be overwritten)"
   inspect_args
 
+  if [ ${args[--app]} == "db" ]; then
+    echo "reach db"
+    package_name="db"
+    comps=''
+    eval "comps=(${args[components]})"
+    for i in "${comps[@]}"; do
+      package_name="${package_name}_${i}"
+    done
+    echo $package_name
+    output_dir=`pwd`
+    echo $output_dir
+    build_dir=`mktemp -d`
+    pushd $build_dir
+    cmd="cmake -DCPACK_PACKAGE_NAME=${package_name} ${output_dir} && make -j && make package && mv ${package_name}*.deb ${output_dir}/"
+    echo $cmd
+    eval $cmd
+    popd
+  else
+    echo "not reach db"
+  fi
+
   # TODO: parse args and make.
-  echo "artifact: graphscope_flex_${args[--app]}_"+${$comps// /_}+".deb is built."
+  # echo "artifact: graphscope_flex_${args[--app]}_"+${$comps// /_}+".deb is built."
 
 }
 
@@ -38,50 +59,43 @@ flexbuild_usage() {
 
   fi
 
-  printf "Usage:\n"
-  printf "  flexbuild [SOURCE] [OPTIONS]\n"
+  printf "%s\n" "Usage:"
+  printf "  flexbuild COMPONENTS... [OPTIONS]\n"
   printf "  flexbuild --help | -h\n"
   printf "  flexbuild --version | -v\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "Options:\n"
-
-    # :command.usage_fixed_flags
-    echo "  --help, -h"
-    printf "    Show this help\n"
-    echo
-    echo "  --version, -v"
-    printf "    Show version number\n"
-    echo
+    printf "%s\n" "Options:"
 
     # :command.usage_flags
     # :flag.usage
-    echo "  --app, -a ATYPE (required)"
+    printf "  %s\n" "--app, -a ATYPE (required)"
     printf "    Application type.\n"
     printf "    Allowed: db, olap\n"
     echo
 
-    # :flag.usage
-    echo "  --components, -c CPNS (required) (repeatable)"
-    printf "    Selected components for Flex build\n"
-    printf "    Allowed: cppsp, hiactor, mcsr, grape\n"
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+    printf "  %s\n" "--version, -v"
+    printf "    Show version number\n"
     echo
 
     # :command.usage_args
-    printf "Arguments:\n"
+    printf "%s\n" "Arguments:"
 
     # :argument.usage
-    echo "  SOURCE"
-    printf "    SOURCE_DIR to build\n"
-    printf "    Default: .\n"
+    printf "  %s\n" "COMPONENTS..."
+    printf "    components to include and link\n"
     echo
 
     # :command.usage_examples
-    printf "Examples:\n"
-    printf "  ./flexbuild --app db -c cppsp -c hiactor\n"
-    printf "  ./flexbuild --app olap --components grape\n"
+    printf "%s\n" "Examples:"
+    printf "  ./flexbuild cppsp hiactor --app db\n"
+    printf "  ./flexbuild grape --app olap\n"
     echo
 
   fi
@@ -113,8 +127,8 @@ normalize_input() {
 }
 # :command.inspect_args
 inspect_args() {
-  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
   if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
     for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
@@ -129,6 +143,14 @@ inspect_args() {
       echo "- \${other_args[$i]} = ${other_args[$i]}"
     done
   fi
+
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
+    echo
+    echo deps:
+    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+  fi
+
 }
 
 # :command.command_functions
@@ -178,25 +200,6 @@ parse_requirements() {
         fi
         ;;
 
-      # :flag.case
-      --components | -c)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-
-          if [[ -z ${args['--components']+x} ]]; then
-            args['--components']="\"$2\""
-          else
-            args['--components']="${args[--components]} \"$2\""
-          fi
-          shift
-          shift
-        else
-          printf "%s\n" "--components requires an argument: --components, -c CPNS" >&2
-          exit 1
-        fi
-        ;;
-
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -204,14 +207,14 @@ parse_requirements() {
 
       *)
         # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        if [[ -z ${args['source']+x} ]]; then
+        # :command.parse_requirements_case_repeatable
 
-          args['source']=$1
+        if [[ -z ${args['components']+x} ]]; then
+          args['components']="\"$1\""
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
-          exit 1
+          args['components']="${args[components]} \"$1\""
+          shift
         fi
 
         ;;
@@ -219,31 +222,23 @@ parse_requirements() {
     esac
   done
 
+  # :command.required_args_filter
+  if [[ -z ${args['components']+x} ]]; then
+    printf "missing required argument: COMPONENTS\nusage: flexbuild COMPONENTS... [OPTIONS]\n" >&2
+    exit 1
+  fi
+
   # :command.required_flags_filter
   if [[ -z ${args['--app']+x} ]]; then
     printf "missing required flag: --app, -a ATYPE\n" >&2
     exit 1
   fi
-  if [[ -z ${args['--components']+x} ]]; then
-    printf "missing required flag: --components, -c CPNS\n" >&2
-    exit 1
-  fi
-
-  # :command.default_assignments
-  [[ -n ${args['source']:-} ]] || args['source']="."
 
   # :command.whitelist_filter
-  if [[ ! ${args['--app']} =~ ^(db|olap)$ ]]; then
+  if [[ ${args['--app']} ]] && [[ ! ${args['--app']} =~ ^(db|olap)$ ]]; then
     printf "%s\n" "--app must be one of: db, olap" >&2
     exit 1
   fi
-  eval "input_array=(${args[--components]})"
-  for i in "${input_array[@]}"; do
-    if [[ ! $i =~ ^(cppsp|hiactor|mcsr|grape)$ ]]; then
-      printf "%s\n" "--components must be one of: cppsp, hiactor, mcsr, grape" >&2
-      exit 1
-    fi
-  done
 
 }
 
@@ -260,16 +255,14 @@ initialize() {
 # :command.run
 run() {
   declare -A args=()
+  declare -A deps=()
   declare -a other_args=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
   case "$action" in
-    "root")
-      root_command
-      ;;
-
+    "root") root_command ;;
   esac
 }
 
