add store script

diff --git a/interactive_engine/bin/giectl b/interactive_engine/bin/giectl
--- a/interactive_engine/bin/giectl
+++ b/interactive_engine/bin/giectl
@@ -615,6 +615,118 @@ stop_service() {
   fi
 }
 
+_setup_maxgraph_env() {
+  if [ ! -n "${GRAPHSCOPE_RUNTIME}" ]; then
+    export GRAPHSCOPE_RUNTIME=/tmp/graphscope/runtime
+  fi
+
+  export LD_LIBRARY_PATH=${GRAPHSCOPE_HOME}/native:${LD_LIBRARY_PATH}:/usr/local/lib
+
+  log_dir=${GRAPHSCOPE_RUNTIME}/logs
+  mkdir -p ${log_dir}
+
+  libpath="$(echo "${GRAPHSCOPE_HOME}"/lib/*.jar | tr ' ' ':')"
+}
+
+max_node() {
+  type=$1
+  log_name=$2
+  config_file=$3
+  shift 3
+
+  _setup_maxgraph_env
+
+  if [[ "${typr}" == "gaia" ]]; then
+    java -server \
+         -Dlogback.configurationFile="${WORKSPACE}/config/logback.xml" \
+         -Dconfig.file="${config_file}" \
+         -Dlog.dir="${log_dir}" \
+         -Dlog.name="${log_name}" \
+         -cp "${libpath}" com.alibaba.graphscope.gaia.MaxNode \
+         "$@" > "${log_dir}/${log_name}.out" 2>&1 <&- &
+  else
+    java -server \
+         -Dlogback.configurationFile="${WORKSPACE}/config/logback.xml" \
+         -Dconfig.file="${config_file}" \
+         -Dlog.dir="${log_dir}" \
+         -Dlog.name="${log_name}" \
+         -cp "${libpath}" com.alibaba.maxgraph.v2.MaxNode \
+         "$@" > "${log_dir}/${log_name}.out" 2>&1 <&- &
+  fi
+
+  pid=$!
+  if ! ps -p $pid > /dev/null ; then
+    err "max node $type start failed."
+    exit 1
+  fi
+}
+
+admin_tools() {
+  log_name=$1
+  config_file=$2
+  shift 2
+
+  _setup_maxgraph_env
+
+  java_opt="-server ${MAXGRAPH_JAVA_OPTS}"
+  java ${java_opt} \
+      -Dlogback.configurationFile="${WORKSPACE}/logback.xml" \
+      -Dconfig.file="${config_file}" \
+      -Dlog.dir="${log_dir}" \
+      -Dlog.name="${log_name}" \
+      -cp "${libpath}" com.alibaba.maxgraph.v2.AdminTools \
+      "$@"
+}
+
+load_tools() {
+  _setup_maxgraph_env
+  java -cp "${WORKSPACE}/lib/data_load_tools-0.0.1-SNAPSHOT.jar" \
+       com.alibaba.maxgraph.dataload.LoadTool "$@"
+}
+
+maxgraph() {
+  log_name=$1
+  config_file=$2
+  shift 2
+
+  _setup_maxgraph_env
+
+  java_opt="-server
+            -Djava.awt.headless=true
+            -Dfile.encoding=UTF-8
+            -Dsun.jnu.encoding=UTF-8
+            -XX:+UseG1GC
+            -XX:ConcGCThreads=2
+            -XX:ParallelGCThreads=5
+            -XX:MaxGCPauseMillis=50
+            -XX:InitiatingHeapOccupancyPercent=20
+            -XX:-OmitStackTraceInFastThrow
+            -XX:+HeapDumpOnOutOfMemoryError
+            -XX:HeapDumpPath=${log_dir}/${log_name}.hprof
+            -XX:+PrintGCDetails
+            -XX:+PrintGCDateStamps
+            -XX:+PrintTenuringDistribution
+            -XX:+PrintGCApplicationStoppedTime
+            -Xloggc:${log_dir}/${log_name}.gc.log
+            -XX:+UseGCLogFileRotation
+            -XX:NumberOfGCLogFiles=32
+            -XX:GCLogFileSize=64m"
+
+  java ${java_opt} \
+      -Dlogback.configurationFile="${WORKSPACE}/logback.xml" \
+      -Dconfig.file=${config_file} \
+      -Dlog.dir="${log_dir}" \
+      -Dlog.name="${log_name}" \
+      -cp "${libpath}" com.alibaba.maxgraph.v2.MaxGraph \
+      "$@" > "${log_dir}/${log_name}.out" 2>&1 <&- &
+
+  pid=$!
+  if ! ps -p $pid > /dev/null ; then
+    err "maxgraph start failed."
+    exit 1
+  fi
+}
+
 # parse argv
 while test $# -ne 0; do
   arg=$1; shift
@@ -629,6 +741,11 @@ while test $# -ne 0; do
     start_coordinator) start_coordinator "$@"; exit;;
     start_frontend) start_frontend "$@"; exit;;
     start_executor) start_executor "$@"; exit;;
+    max_node_gaia) max_node "gaia" "$@"; exit;;
+    max_node_maxgraph) max_node "maxgraph" "$@"; exit;;
+    maxgraph) max_graph "$@"; exit;;
+    admin_tools) admin_tools "$@"; exit;;
+    load_tools) load_tools "$@"; exit;;
     *)
       echo "unrecognized option or command '${arg}'"
       usage; exit;;
