Fix mac nightly CI (#2436)

diff --git a/.github/workflows/build-graphscope-wheels-macos.yml b/.github/workflows/build-graphscope-wheels-macos.yml
--- a/.github/workflows/build-graphscope-wheels-macos.yml
+++ b/.github/workflows/build-graphscope-wheels-macos.yml
@@ -1,5 +1,6 @@
 name: Build GraphScope Wheels on MacOS
 
+# on: [push, pull_request]
 on:
   workflow_dispatch:
   schedule:
@@ -20,9 +21,6 @@ jobs:
       with:
         submodules: true
 
-    - name: Setup tmate session
-      if: false
-      uses: mxschmitt/action-tmate@v2
 
     - name: Install Dependencies
       run: |
@@ -30,12 +28,33 @@ jobs:
         # fixed protobuf version 3.17.3
         git checkout 2b411d925849478163647594b32fd237828cf720
         popd
-        ${GITHUB_WORKSPACE}/scripts/install_deps.sh --dev --vineyard_prefix /opt/vineyard --verbose
+        brew install bash
+        alias bash=$(brew --prefix)/bin/bash
+        sudo mkdir /opt/graphscope
+        sudo chown -R $(id -u):$(id -g) /opt/graphscope
+        # This will install vineyard by homebrew
+        # But we need to install vineyard to /opt/vineyard, so install it from source again.
+        
+        # Not sure when the first installation would fail, saying that the lock of python3.10 is taken
+        # However the second trial would success.
+        ./gs install-deps dev --no-v6d || true
+        ./gs install-deps dev --no-v6d
+
+    - name: Install latest libgrape-lite
+      if: true
+      run: |
+        source ~/.graphscope_env
+        git clone --single-branch --depth=1 https://github.com/alibaba/libgrape-lite.git /tmp/libgrape-lite
+        cd /tmp/libgrape-lite
+        cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
+        make -j4
+        sudo make install
 
     - name: Build Server Wheel
       run: |
         # source environment variable
         source ~/.graphscope_env
+        python3 -m pip install libclang
         echo ${CC}
 
         # change the version for nightly release
@@ -44,13 +63,19 @@ jobs:
         version=$(cat ${GITHUB_WORKSPACE}/VERSION)
         if [ "${{ GITHUB.REF }}" == "refs/heads/main" ];then echo "${version}a${time}" > ${GITHUB_WORKSPACE}/VERSION; fi
 
+        python3 -m pip install numpy "pandas<1.5.0" "grpcio<=1.43.0,>=1.40.0" "grpcio-tools<=1.43.0,>=1.40.0" wheel
+
         # build graphscope server wheel
         cd ${GITHUB_WORKSPACE}/k8s/internal
-        sudo -E make graphscope-py3-package GRAPHSCOPE_HOME=/opt/graphscope INSTALL_PREFIX=${GITHUB_WORKSPACE}/install
+        sudo -E make graphscope-py3-package GRAPHSCOPE_HOME=/opt/graphscope
 
         # package
         cd ${GITHUB_WORKSPACE}
         tar -zcf graphscope.tar.gz coordinator/dist/wheelhouse/*.whl
+
+    - name: Setup tmate session
+      if: failure()
+      uses: mxschmitt/action-tmate@v2
 
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
@@ -82,7 +107,41 @@ jobs:
         # fixed protobuf version 3.17.3
         git checkout 2b411d925849478163647594b32fd237828cf720
         popd
-        ${GITHUB_WORKSPACE}/scripts/install_deps.sh --dev --verbose
+        brew install bash
+        alias bash=$(brew --prefix)/bin/bash
+        sudo mkdir /opt/graphscope
+        sudo chown -R $(id -u):$(id -g) /opt/graphscope
+
+        # Not sure when the first installation would fail, saying that the lock of python3.10 is taken
+        # However the second trial would success.
+        ./gs install-deps dev --no-v6d || true
+        ./gs install-deps dev --no-v6d
+
+    - name: Install latest libgrape-lite
+      if: true
+      run: |
+        source ~/.graphscope_env
+        git clone --single-branch --depth=1 https://github.com/alibaba/libgrape-lite.git /tmp/libgrape-lite
+        cd /tmp/libgrape-lite
+        cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
+        make -j4
+        sudo make install
+
+    - name: Install latest vineyard
+      if: true
+      run: |
+        source ~/.graphscope_env
+        python3 -m pip install libclang
+        git clone --single-branch -b v0.12.2 --depth=1 https://github.com/v6d-io/v6d.git /tmp/v6d
+        cd /tmp/v6d
+        git submodule update --init
+        cmake .  -DCMAKE_INSTALL_PREFIX=/usr/local \
+                 -DCMAKE_PREFIX_PATH=/usr/local \
+                 -DUSE_EXTERNAL_ETCD_LIBS=OFF \
+                 -DBUILD_SHARED_LIBS=ON \
+                 -DBUILD_VINEYARD_TESTS=OFF
+        make -j4
+        sudo make install
 
     - name: Build Client Wheels
       run: |
